/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/chair/scene.gltf 
Author: brucassol (https://sketchfab.com/brucassol)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chair-327203d10f524ed2aac78e59546821b3
Title: Chair
*/

import { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";
import { useCustomization } from "../contexts/CustomizationCtx";

export function Chair(props) {
  const { material, chairColor } = useCustomization();

  const group = useRef();
  const { nodes, materials } = useGLTF("./models/chair/scene.gltf");

  const leatherProps = useTexture({
    // map: "./textures/leather/Leather_008_Base Color.jpg",
    displacementMap: "./textures/leather/Leather_008_Height.png",
    normalMap: "./textures/leather/Leather_008_Normal.jpg",
    roughnessMap: "./textures/leather/Leather_008_Roughness.jpg",
    aoMap: "./textures/leather/Leather_008_Ambient Occlusion.jpg",
  });

  const knitProps = useTexture({
    // map: "./textures/knit/Fabric_Knitted_006_basecolor.jpg",
    displacementMap: "./textures/knit/Fabric_Knitted_006_height.png",
    normalMap: "./textures/knit/Fabric_Knitted_006_normal.jpg",
    roughnessMap: "./textures/knit/Fabric_Knitted_006_roughness.jpg",
    aoMap: "./textures/knit/Fabric_Knitted_006_ambientOcclusion.jpg",
  });

  // leatherProps.map.repeat.set(3, 3);
  leatherProps.displacementMap.repeat.set(3, 3);
  leatherProps.normalMap.repeat.set(3, 3);
  leatherProps.roughnessMap.repeat.set(3, 3);
  leatherProps.aoMap.repeat.set(3, 3);

  // leatherProps.map.wrapS = leatherProps.map.wrapT = THREE.RepeatWrapping;
  leatherProps.displacementMap.wrapS = leatherProps.displacementMap.wrapT =
    THREE.RepeatWrapping;
  leatherProps.normalMap.wrapS = leatherProps.normalMap.wrapT =
    THREE.RepeatWrapping;
  leatherProps.roughnessMap.wrapS = leatherProps.roughnessMap.wrapT =
    THREE.RepeatWrapping;
  leatherProps.aoMap.wrapS = leatherProps.aoMap.wrapT = THREE.RepeatWrapping;

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0.945]}
          scale={0.021}
        >
          <group
            name="7cb4ba39acb74acf8dd12c14f6121175fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Camera"
                  position={[0, 75, 400]}
                  rotation={[-0.087, Math.PI / 2, 0]}
                >
                  <group name="Object_5" />
                </group>
                <group name="Poltrona" position={[0, 0.14, 0]}>
                  <group name="legs">
                    <mesh
                      name="legs_mesh"
                      geometry={nodes["Madeira_(2)_Madeira_0"].geometry}
                      material={materials.Madeira}
                    />
                  </group>
                  <group name="leather" position={[0, 1.5, -0.6]}>
                    <mesh
                      name="leather_mesh"
                      geometry={nodes.Almofada_Couro_0.geometry}
                      // material={materials.Couro}
                    >
                      <meshStandardMaterial
                        {...(material === "leather" ? leatherProps : knitProps)}
                        color={chairColor.color}
                      />
                    </mesh>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
export default Chair;
